### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'started'

### ISSUE THREAD

**Issue by decapo01** [aio-libs/aiohttp-session#167]
I'm using version 0.5.0 with python 3.6.  I've followed the example code and am using the cookie storage.  I keep getting the error AttributeError: 'Response' object has no attribute 'started' in ```aiohttp_session/__init__.py", line 138, in middleware```.

Here is my set up code.

```
app = web.Application()

aiohttp_jinja2.setup(
    app, loader=jinja2.FileSystemLoader('MyApp/templates')
)

fernet_key = fernet.Fernet.generate_key()
secret_key = base64.urlsafe_b64decode(fernet_key)
setup(app, EncryptedCookieStorage(secret_key))

web.run_app(app, port=8000)
```

the error occurs only when I try to load any page registerd in the app.

**Comment by panagiks** [comment]
Hello,

from a quick look into t[he code and its git history](https://github.com/aio-libs/aiohttp-session/commit/b76ea3b8c7690907c9aaee3c49cc293730d49606) you can see that resp.started was dropped before v0.6.0 and from a look to [aiohttp's changelog](http://aiohttp.readthedocs.io/en/stable/changes.html#rc1-2017-03-15) Response.started has been discontinued since 2017-03-15. As a result if you are using aiohttp 2.0.0 or higher you will have to use at least v0.6.0 of aiohttp_session. It's always a good idea to use the latest version since continuous integration guarantees that it will work with latest versions of the dependencies. Is there a constraint that leads to the use of an older version of aiohttp_session (v0.5.0)?
Hope this helps :)

**Comment by decapo01** [comment]
That was it.  I was looking at the releases and the newest version appeared to be 0.5.0.  I upgraded to 0.8.0 and everything works as expected.
