### ISSUE TITLE
Remove session key from redis by session.invalidate

### ISSUE THREAD

**Issue by achernetsky** [aio-libs/aiohttp-session#258]
Hello,

**Actual behaviour**

Key from redis does not deleted after session is invalidate.

**Expected behaviour**

Key from redis deleted after session is invalidate.

What do you think about it?

```python
class LogoutView(BaseView):
   async def post(self):
       session = await aiohttp_session.get_session(self.request)
       session.invalidate()
```

Thanks.

**Comment by panagiks** [comment]
Hi,

Are you describing the fact that after `session.invalidate()` the key still exists in Redis, but with an empty value?

If so this seems to be the approach in every storage (and not Redis specific), at least from a quick look.

I don't know if this was intentional (by design), but personally I utilize this difference (existent keys with empty values vs non existent keys) to differentiate between invalidated and non-existent/expired sessions.

**Comment by achernetsky** [comment]
@panagiks,

Thanks for your response.

Yes, I saw this fact. After call `session.invalidate()` in redis exist `{}` value by session key.

```
127.0.0.1:6379[1]> GET SESSION_zl4ljXErUeSBVnFxi9t7ewNZl4afys
"{}"
```

> I don't know if this was intentional (by design), but personally I utilize this difference (existent keys with empty values vs non existent keys) to differentiate between invalidated and non-existent/expired sessions.

An interesting approach!

But it is bug or future?)

**Comment by asvetlov** [comment]
The behavior is not redis specific. `session.invalidate()` doesn't delete the session but makes it empty.

Let's consider it as a feature.

**Comment by achernetsky** [comment]
OK. I understood. But I think method which removes (deletes key from redis, memcached or something else) session (when it is not needed) can be useful.

**Comment by endlessmeal** [comment]
So, how did you delete the key entirely?
