### ISSUE TITLE
simple await new_session(request) can't store a new session

### ISSUE THREAD

**Issue by Trim21** [aio-libs/aiohttp-session#319]
expected beheavior: 
all session key should be deleted after 
```
class Logout(web.View):
    async def get(self):
        session = await new_session(request=self.request)
        # session['login'] = False
        return web.HTTPFound('/')
```
infact: the session keep what it is, only i set a value manually like `session['login'] = False` the server will send `set-cookies` header

python3.7 aiohttp3.4.4 aiohttp-session2.6.0

**Comment by Trim21** [comment]
I read the source code and i fount

```
def session_middleware(storage):
    ...
        if session is not None:
            if session._changed:
                await storage.save_session(request, response, session)
        if raise_response:
            raise response
        return response

    return factory
```

it seems that it is indeed beheavior, but i think it's pretty confusing

**Comment by panagiks** [comment]
Hello @Trim21,

a few notes here.

1) On logout you should not return a new session but invalidate the one presented to you.
2) `new_session` is to be used on `login` view as clearly stated in [documentation](https://aiohttp-session.readthedocs.io/en/latest/reference.html#aiohttp_session.new_session)
3) As you note from the source code it is the expected behavior to only store changed session, otherwise (in case of external storage, i.e. redis / memcached) you would spam your storage with 'writes' on every request.

So for your use case I would suggest you use [session.invalidate](https://aiohttp-session.readthedocs.io/en/latest/reference.html#aiohttp_session.Session.invalidate).

Regards,
panagiks

**Comment by Trim21** [comment]
thank you, I'll close the issue.
