### ISSUE TITLE
Session keeps been resetting after max_age exceeded

### ISSUE THREAD

**Issue by hubo1016** [aio-libs/aiohttp-session#344]
https://github.com/aio-libs/aiohttp-session/blob/b9a5f9cc82e8d1adb541d4dd9e64603b7b4360c0/aiohttp_session/__init__.py#L30

At least we must set `_updated = True` to let the storage save the new empty session, so it is equivalent to call `session.invalidate()`. The current implementation makes it a *magic session* which seems valid, can save new data, but magically clear them when loading. This is very confusing.

**Comment by panagiks** [comment]
Hello @hubo1016 and thank you for the report :)

From what I can tell from a first look you are correct. I think that this is due to other attributes (like created) not being reset however. The idea is that if an expired session is provided a completely new should be created. I will look into it further in the following days.

In the meantime however, in order to reach this case it means (as far as I can tell) that the client that presented your server with this session is either not respecting cookie expiry (and is thus presenting you with an expired session) or is recreating an expired cookie (which I would personally consider malicious). 

Do you have any information as to how / why a client sends you an expired session?

Regards,
panagiks

**Comment by hubo1016** [comment]
@panagiks It is because the other part of the implementation uses `max_age` as an idle timeout. When the session is stored in redis, and the cookies is sent to the client, the expiration time is refreshed - but `created` is not. So if the session is touched before expiration, this piece of code will "clear" the session before expiration.

**Comment by panagiks** [comment]
Hi @hubo1016 

As also mentioned in #332 the `idle timeout` logic was broken with #331 by me (as I was not aware of it as an expected behavior).  This should be properly addressed (I try to find some time to make a well thought out PR to fix this and not something rushed).

To be clear however, under no circumstances should a `client` application `recreate` a cookie that has expired. This a non-RFC compliant behavior. See [RFC6265-sec5.3](https://tools.ietf.org/html/rfc6265#section-5.3):

> A cookie is "expired" if the cookie has an expiry date in the past.
   The user agent MUST evict all expired cookies from the cookie store
   if, at any time, an expired cookie exists in the cookie store.

**Comment by hubo1016** [comment]
@panagiks It is **not** `receated`, it is a valid cookie and a valid session which never expires, because when the session data is modified, the expiration time of the cookie and the session is refreshed, but the `created` timestamp in Redis (or other storage) is not refreshed, so it is considered expired by your code.

This issue is **not** generated by a buggy client or some wired client-side script. It is triggered by a normal browser. Following steps should easily reproduce this issue:

1. Configure the session system with a low max_age (5s e.g.)
2. Write a simple handler that test and touch the session
3. Keep refreshing the page in a browser

An example handler may be something like:

```python
async def hello(request):
    session = await get_session(request)
    data = session.get('data', 'new')
    session['data'] = 'old'
    return Response(text=data)
```

When keep refreshing the page (interval < max_age), you should see "new" once, and "old" later, but after `max_age`, you will always see "new". It can only be fixed by letting the cookies expires in another `max_age` or clearing them from browser manually.
