### ISSUE TITLE
Possible incorrect max_age check on session initialization

### ISSUE THREAD

**Issue by kreopt** [aio-libs/aiohttp-session#348]
Looks like it's a typo in __init__.py:28.

`age = now - created if created else now `

should be 

`age = now - (created if created else now)`

Else, session with `max_age` set but `created=None` is always cleaned up on initialization.

**Comment by panagiks** [comment]
Hello @kreopt ,

From where I see it a session with `created == None` is either an invalid one or an empty one since `created` is not user provided input but metadata inserted by `aiohttp-session`. see:

https://github.com/aio-libs/aiohttp-session/blob/b9a5f9cc82e8d1adb541d4dd9e64603b7b4360c0/aiohttp_session/__init__.py#L212

Looking at how session objects are created, it is either that a new session is created (so it should be empty and filled with data once the initialization is completed) or that an existing session is loaded. In the second case the `created` key should exist within the `data` kwarg passed to `__init__`.

There might be some case I'm failing to see here however. Could you provide some code sample where a valid session is loaded with `max_age` set and `created == None`?

Regards,
panagiks

**Comment by hubo1016** [comment]
I think it is not the problem of whether it **works**, but whether it is **correct**. 

```python
age = now - created if created else now
```

means

```python
age = (now - created) if created else now
```

`age` should definitely not a **interval** when `created == True` but a **timestamp** when `created == False`. Even if you want it to be expired, you should not write a code like this. What happens when `max_age` is very large like 100 years, even larger than current `now`? Currently the session will not expire, but it expires years later. It does not make sense.

**Comment by kreopt** [comment]
I create session with such code to pass some info from session manager to request handler (for example, identify session manager errors):

`session = Session(None, data={'session': {...}}, new=True, max_age=self.max_age)`

what's going on in constructor? 
`
created = data.get('created', None) if data else None # become None
age = now - created if created else now # become now
if max_age is not None and age > max_age: # True and True because age = now and max_age is interval in second
     session_data = None # so, here session_data passed in constructor is cleaned up
`
Maybe this is conceived behavior but I don't understand why we should erase passed session data. In my opinion, this looks not very clear and there are two ways to create correct session with data: even specify "session" and "created" keys in data or create session, then set value with session[key] = ...

**Comment by Dreamsorcerer** [comment]
I think this is the safer thing to do. If there is a max_age and no created date, then it is safer to assume that the session has expired, rather than risk using an expired session. Basically, I think the expectation is that "created" should always be present if `max_age` is set (we could probably even add that to the annotations with `@overload`s).
