### ISSUE TITLE
document bug in homepage that always return a download

### ISSUE THREAD

**Issue by NewUserHa** [aio-libs/aiohttp-session#368]
https://aiohttp-session.readthedocs.io/en/latest/
```
import time
from aiohttp import web
from aiohttp_session import get_session, setup
from aiohttp_session.cookie_storage import EncryptedCookieStorage

async def handler(request):
    session = await get_session(request)
    session['last_visit'] = time.time()
    return web.Response(body=b'OK')

def init():
    app = web.Application()
    setup(app,
        EncryptedCookieStorage(b'Thirty  two  length  bytes  key.'))
    app.router.add_route('GET', '/', handler)
    return app

web.run_app(init())
```
`return web.Response(body=b'OK')` will return a download file to my chrome.

considering fix?

**Comment by panagiks** [comment]
Hello @NewUserHa and thank you for the report.

What is the expected behavior here ? Does `aiohttp-session` affect the current behavior, if for example you run the following code is the behavior the same?

```py
from aiohttp import web

async def handler(request):
    return web.Response(body=b'OK')

def init():
    app = web.Application()
    app.router.add_route('GET', '/', handler)
    return app

web.run_app(init())
```

If the above code exhibits the same behavior as your code then your question is better directed towards `aiohttp`. But I think the most important question is what you would expect the above example to do (regardless of whether it is related to `aiohttp` or `aiohttp-session`).

Regards,
panagiks

**Comment by NewUserHa** [comment]
this code is an example on the homepage so it might want to show the code work.
replace `return web.Response(body=b'OK')` with `return web.Response(body='OK')` will just show a text.
don't you think this is the proper example?

**Comment by panagiks** [comment]
I still don't see how the code 'doesn't work'. This is a session library, the whole point of the example is to showcase a cookie being set and the example works pretty well at that.

Having said that since this specific example is the only place (throughout `aiohttp-session` examples / docs) I can find a `bytes` object being provided to the `web.Response` object I will open a merge request to change it for the sake of uniformity.

**Comment by NewUserHa** [comment]
maybe typo. what I wanted to say is it should be `return web.Response(body='OK')` instead a download(bytes).
